### ISSUE TITLE
mitm.it says 404 not found

### ISSUE THREAD

**Issue by lokislokis** [KennethWussmann/recon-bolt-proxy#3]
got everything working up until the part where I have to go to mitm.it

everytime i load the page on mitm.it it simply says "404 not found at the top left corner"

**Comment by KennethWussmann** [comment]
1. Make sure the docker container is running using `docker compose up` in the directory where you put the YAML file. 
2. Check that your phone and computer are on the same network and that they can reach each other. You can use an [app on your iPhone](https://apps.apple.com/de/app/network-analyzer/id562315041) to ping the IP address of your computer to ensure they can see each other.
3. If you did everything correctly the mitm.it page on your iPhone should look like this: ![](https://www.dinofizzotti.com/blog/2022-04-24-running-a-man-in-the-middle-proxy-on-a-raspberry-pi-4/mitm_cert_install.PNG)
4. Follow the instructions on the page listed under `iOS`

The issue is not related to `recon-bolt-proxy`
