### ISSUE TITLE
no internet

### ISSUE THREAD

**Issue by SahilJain8** [KennethWussmann/recon-bolt-proxy#4]
when  the  connect to the proxy on my phone i loss internet access

**Comment by KennethWussmann** [comment]
1. Make sure the docker container is running using `docker compose up` in the directory where you put the YAML file. 
2. Check that your phone and computer are on the same network and that they can reach each other. You can use an [app on your iPhone](https://apps.apple.com/de/app/network-analyzer/id562315041) to ping the IP address of your computer to ensure they can see each other.
3. If you did everything correctly the mitm.it page on your iPhone should look like this: ![](https://www.dinofizzotti.com/blog/2022-04-24-running-a-man-in-the-middle-proxy-on-a-raspberry-pi-4/mitm_cert_install.PNG)
4. Follow the instructions on the page listed under `iOS`

The issue is not related to `recon-bolt-proxy`
